In [7]:
import torch
import numpy as np

In [8]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [9]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [10]:
data[0] = 0
data[1] = 0
data[2] = 0

In [12]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [13]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


the first two tensors contain the original values
changing the array after the fact, didnt change the tensor data

the second two tensors contain the same data that is in the array after the change

this change is determined to how the different objects are created under the memory
the first two create a copy of the array and save it seperately

the second two share the data with the numpy array

given all this information it is advised to use the torch.tensor factory function in everday use, but for optimising for performance, it is advised to use the torch.as_tensor factory function as no memory copying is needed