In [2]:
import torch
import numpy as np

In [3]:
t = torch.Tensor()
type(t)

torch.Tensor

For PyTorch we have
1. data type
2. device
3. layout

In [5]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


The data type for each tensor must be the same for any arithmetic operation to be applied to both of them

the device between each tensor must also be the same to prevent error

the strided layout is the most popular and default layout so this is not changed

In [6]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [7]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [8]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

each of these different functions for initialising a tensor object are different and the Tensor functions specifically is seen to produce a different variable type to that which was input to the numpy array

In [11]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [13]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [14]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [18]:
torch.rand(2,2)

tensor([[0.8683, 0.6877],
        [0.0221, 0.3937]])

each of these four inbuilt PyTorch functions make it possible to produce a tensor without any data before hand