In [2]:
import torch
import numpy as np

In [3]:
t = torch.Tensor()
type(t)

torch.Tensor

For PyTorch we have: data type, device, layout

The data type for each tensor must be the same for any arithmetic operation to be applied to both of them

the device between each tensor must also be the same to prevent error

the strided layout is the most popular and default layout so this is not changed

In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [5]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

Each of these different functions for initialising a tensor object are different and the Tensor functions specifically is seen to produce a different variable type to that which was input to the numpy array

deciding which of these tensor constructors to use is dependent on their methods of producing and tensor

the first Tensor, is a class constructors

the other three are factory functions, a factory fuction is a function which accepts particular parameter inputs and then returns a specific object output they are an OOP theory for making objects

the factory functions are therefore preferred as they contain more documentation and they infer the data type of the input

In [6]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [7]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [8]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


here it can be seen that the Tensor constructor produces a different data type to that which is used by the the factory functions,

this is because the factory functions have data inference, and the class constructor uses the default tensor data type of float32

when the tensor is initialised, the data type can be specified in the factory function parameters

In [9]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

even though the numpy array passed through integer to the tensor, the data type was specified as float, and so that was output

each of these four inbuilt PyTorch functions make it possible to produce a tensor without any data before hand

In [10]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [11]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [13]:
torch.rand(2,2)

tensor([[0.6463, 0.2741],
        [0.8349, 0.3656]])