In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [3]:
t1[0][0]

tensor(1.)

In [4]:
t2[0][0]

tensor(9.)

these two values are corresponding elements between the two tensors of the same shape and rank

given these similar properties it is possible to perform element-wise operations

In [5]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [6]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [7]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [8]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

here the tensor being a vector value undergoes an arithmetic operation with a scalar value. this shouldnt work as they are different shapes and are of different rank.

however, the scalar value is compared to the tensor, and a copy of the tensor is made, using the scalar quantity value. an element-wise arithmetic operation is made on each corresponding value in the two tensors.

this known as being broadcast to have the same dimensions as the t1 tensor  

In [9]:
t3 = torch.tensor([
    [1,1],
    [2,2]
], dtype=torch.float32)

t4 = torch.tensor([2,4], dtype=torch.float32)

In [10]:
np.broadcast_to(t4.numpy(), t3.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [11]:
t3 + t4

tensor([[3., 5.],
        [4., 6.]])

the two tensors are of different shape and the broadcasting fuction allows arithmetic operation between the two

the operation is carried out element-wise

In [12]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [13]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [14]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

it can be seen that the comparison operation of less than 7 is a broadcasting function of creating the same shaped tensor from the scalar 7 and the same dimension, then comparing each scalar value element-wise

In [15]:
t = torch.tensor([
    [1,0,1],
    [2,2,3],
    [0,0,5]
], dtype=torch.float32)

In [16]:
t.sum()

tensor(14.)

In [17]:
t.prod()

tensor(0.)

In [18]:
t.mean()

tensor(1.5556)

In [19]:
t.std()

tensor(1.6667)

these are all reduction operations, a process which occurs within the same tensor and reduces the number of elements in the tensor

each of these have been reduced to a one value tensor via arithmetic operation, but most reductions are performed on specific dimensions

In [20]:
t1 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [21]:
t1.sum(dim=0)

tensor([6., 6., 6., 6.])

In [22]:
t1.sum(dim=1)

tensor([ 4.,  8., 12.])

when we take respects to the first axis, we are summing the elements of the axis

In [23]:
t1[0] + t1[1] + t1[2]

tensor([6., 6., 6., 6.])

In [24]:
t1[0].sum()

tensor(4.)

In [25]:
t1[1].sum()

tensor(8.)

In [26]:
t1[2].sum()

tensor(12.)

these individual operations show the element-wise arithmatic used for the different sum dimensions

In [27]:
t2 = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [28]:
t2.max()

tensor(5.)

In [29]:
t2.argmax()

tensor(11)

In [30]:
t2.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

the argmax function finds the index of the maximum value in the tensor dimension given,
this is indentified as 5

given no parameters were specified for the argmax function, the index is given in terms of the one dimensional form of the tensor

In [31]:
t2.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [32]:
t2.argmax(dim=0)

tensor([2, 1, 1, 2])

In [33]:
t2.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [34]:
t2.argmax(dim=1)

tensor([3, 2, 3])

these different dimensions being targeted returns different maximum value indexes

In [35]:
t3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [36]:
t3.mean()

tensor(5.)

In [37]:
t3.mean().item()

5.0

In [38]:
t3.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [39]:
t3.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

here the item() function allows specific identication of elements in the tensor and only operates on scalar values

the tolist() function produces an array from the elements in the given dimension

