In [ ]:
import torch
import numpy as np

In [ ]:
t = torch.Tensor()
type(t)

For PyTorch we have: data type, device, layout

The data type for each tensor must be the same for any arithmetic operation to be applied to both of them

the device between each tensor must also be the same to prevent error

the strided layout is the most popular and default layout so this is not changed

In [ ]:
print(t.dtype)
print(t.device)
print(t.layout)

In [ ]:
data = np.array([1,2,3])
type(data)

Each of these different functions for initialising a tensor object are different and the Tensor functions specifically is seen to produce a different variable type to that which was input to the numpy array

deciding which of these tensor constructors to use is dependent on their methods of producing and tensor

the first Tensor, is a class constructors

the other three are factory functions, a factory fuction is a function which accepts particular parameter inputs and then returns a specific object output they are an OOP theory for making objects

the factory functions are therefore preferred as they contain more documentation and they infer the data type of the input

In [ ]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [ ]:
print(t1)
print(t2)
print(t3)
print(t4)

In [ ]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

here it can be seen that the Tensor constructor produces a different data type to that which is used by the the factory functions,

this is because the factory functions have data inference, and the class constructor uses the default tensor data type of float32

when the tensor is initialised, the data type can be specified in the factory function parameters

In [ ]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

even though the numpy array passed through integer to the tensor, the data type was specified as float, and so that was output

In [ ]:
data[0] = 0
data[1] = 0
data[2] = 0

In [ ]:
print(t1)
print(t2)
print(t3)
print(t4)

the first two tensors contain the original values changing the array after the fact, didnt change the tensor data

the second two tensors contain the same data that is in the array after the change

this change is determined to how the different objects are created under the memory the first two create a copy of the array and save it seperately

the second two share the data with the numpy array

given all this information it is advised to use the torch.tensor factory function in everday use, but for optimising for performance, it is advised to use the torch.as_tensor factory function as no memory copying is needed

In [ ]:
torch.eye(2)

In [ ]:
torch.zeros(2,2)

In [ ]:
torch.ones(2,2)

In [ ]:
torch.rand(2,2)

each of these four inbuilt PyTorch functions make it possible to produce a tensor without any data before hand

In [ ]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

dd

In [ ]:
a1 = torch.tensor(dd)
a1

In [39]:
t5 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
t5

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [40]:
t5.size()

torch.Size([3, 4])

In [41]:
t5.shape

torch.Size([3, 4])

In [42]:
len(t5.shape)

2

the length of the shape object determines its rank, i.e. the number of indexes required to find a number value

In [43]:
torch.tensor(t5.shape).prod()

tensor(12)

In [44]:
t5.numel()

12

both of these operations show the number of items within the tensor, any reshaping must account for all values of the tensor

In [46]:
t5.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [47]:
t5.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

this reshaping changed the rank of the tensor to a rank 3 tensor, as it now requires 3 indexes to specify a number value

In [48]:
print(t5.reshape(1,12))
print(t5.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [49]:
print(t5.reshape(1,12).squeeze())
print(t5.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [51]:
print(t5.reshape(1,12).unsqueeze(dim=0))
print(t5.reshape(1,12).unsqueeze(dim=0).shape)

tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]])
torch.Size([1, 1, 12])


squeezing the tensor removes the axes with a length of one

unsqueezing adds a dimension with a length of one

this is another way of reshaping the tensor

In [52]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [53]:
flatten(t5)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

flattening a tensor is the process of removing all the axes, and reducing the tensor to a one dimensional tensor.
this is required from moving data from a convolutional layer to a fully connected layer

In [54]:
n1 = torch.tensor([
    [1,2],
    [3,4]
])
n2 = torch.tensor([
    [5,6],
    [7,8]
])

In [55]:
torch.cat((n1,n2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [56]:
torch.cat((n1,n2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

this is a Concatenating function, it enables us to increase the number of elements within the resulting tensor 

the first has been applied row wise 

the second has been applied column wise

In [57]:
a1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

a2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

a3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [58]:
a = torch.stack((a1,a2,a3))
a.shape

torch.Size([3, 4, 4])

In [59]:
a

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [60]:
a = a.reshape(3,1,4,4)
a

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

the shape functions has allowed the three rank 2 tensors to be concatenated into a rank 3 tensors

the batch size is 3, the height is 4 and the width is 4

a CNN expects an implicitly stated colour depth therefore it is reshaped to include a 1 under that field

the first dimension image

the second dimension colour channel

the third dimension row of pixels

the last dimension pixel value

In [63]:
a.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [64]:
a.flatten(start_dim=1).shape

torch.Size([3, 16])