In [1]:
import torch
import numpy as np 

In [2]:
a1 = torch.tensor([1,1,1])

In [3]:
a1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [4]:
a1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [5]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [6]:
torch.cat((t1, t2, t3), dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [7]:
torch.stack((t1, t2, t3), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

concatenating tensors is joining along the existing axis

stacking tensors is joining on a new axis

In [8]:
torch.cat((t1.unsqueeze(0), t2.unsqueeze(0), t3.unsqueeze(0)), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [9]:
t1.unsqueeze(0)

tensor([[1, 1, 1]])

In [10]:
t1.unsqueeze(1)

tensor([[1],
        [1],
        [1]])

In [11]:
torch.cat((t1.unsqueeze(1), t2.unsqueeze(1), t3.unsqueeze(1)), dim=0)

tensor([[1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3]])

In [12]:
torch.cat((t1.unsqueeze(1), t2.unsqueeze(1), t3.unsqueeze(1)), dim=1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

1. taking three images as tensors, the images have individual width, height and colour channel values, in order to form one tensor for all three images, they must be stacked in order to preserve the values of the individual axes. the new axis formed is known as the batch axis.

2. then take three images, each of an individual batch of 1. here the images must be concatenated to form one tensor input as only the batch axis will be increased, leaving the individual image specific height, width and colour channels to the same values

3. a batch of three images has already been made, another three individual images have to be added to batch, these new images dont have a batch axis. therefore, the new images must first be stacked to give the batch axis, and then concatenated to the existing three image tensor, forming a tensor with a batch number of 6, and the respective colour channels and image size. this was performed in this order due to the shape of the tensors having to be the same for the concat operation to be performed



In [13]:
t4 = torch.tensor([1,1,1], dtype=torch.float32)
t5 = torch.tensor([2,2,2], dtype=torch.float32)
t6 = torch.tensor([3,3,3], dtype=torch.float32)

batched = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [14]:
new = torch.stack((t4, t5, t6), dim=0)

In [15]:
new

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [16]:
batched

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [17]:
torch.cat((new, batched), dim=0)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])